---
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
    source: "https://github.com/ansible-collections/amazon.aws.git"
    type: git
    version: 7.2.0
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
    source: "https://github.com/ansible-collections/community.vmware.git"
    type: git
    version: 3.9.0
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
  - name: community.hashi_vault
  - name: community.crypto
  - name: community.general
    source: "https://github.com/ansible-collections/community.general.git"
    type: git
    version: 7.5.0
  - name: community.docker
  - name: kubernetes.core
    source: "https://github.com/ansible-collections/kubernetes.core.git"
    type: git
    version: 2.3.2
roles:
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-node-exporter"
    scm: git
    version: main
    name: node_exporter
  - src: "git+https://github.com/SF2311/slm-cc-base"
    scm: git
    version: main
    name: slm_monitoring
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-basyx-server"
    scm: git
    version: main
    name: basyx_server
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-consul"
    scm: git
    version: main
    name: consul
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-inventory-helper"
    scm: git
    version: main
    name: inventory_helper
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-docker"
    scm: git
    version: main
    name: docker
  - src: "git+https://github.com/eclipse-slm/molecule_vsphere"
    scm: git
    version: main
    name: molecule_vsphere